#!/bin/sh

cat | sed -e 's/[ ]*id=\"[^\"]*\"//g;
              s/[ ]*style=\"[^\"]*\"//g;
              s/[ ]*class=\"[^\"]*\"//g;
              s/[ ]*shape=\"[^\"]*\"//g;
              s/&nbsp;//g;
              s/<span[^>]*>//g;
              s#</span>##g;
              s/[ ]*<br[^>]*>/\n/g;
              s/[ ]*<div[^>]*>//g;
              s#[ ]*</div>##g;' \
    | tidy --indent true --wrap 0 --hide-comments true \
           -q 2>/dev/null \
    | sed 's/&Atilde;&frac14;/ü/g;
           s/&Atilde;&curren;/ä/g;
           s/&Atilde;&para;/ö/g;
           s/&Atilde;&ndash;/Ö/g;
           s/&Atilde;&Yuml;/ß/g;
           s/&Atilde;&copy;/é/g;
           s/\&amp;/\&/g;
           s/<font[^>]*>//g;
           s#</font>##g;'


